import type {
  CatalogItemType,
  LivePricingProviderId,
  MarketRegion,
  QuoteCurrency,
} from "./types";

export interface MockPricingFixture {
  fixtureId: string;
  catalogItemId: string;
  catalogItemType: CatalogItemType;
  provider: LivePricingProviderId;
  providerProductId: string;
  setCode?: string;
  cardNumber?: string;
  variant?: string;
  language: string;
  condition: string;
  region: MarketRegion;
  currency: QuoteCurrency;
  primaryPriceField: string | null;
  priceFields: Readonly<Record<string, number | null>>;
  asOf: string;
}

/**
 * Explicit demo-only fixtures. These values are illustrative, are not fetched
 * from either named provider, and must always render with the demo source label.
 */
export const DEMO_PRICING_FIXTURES: readonly MockPricingFixture[] = [
  {
    fixtureId: "demo-cm-op01-001-base",
    catalogItemId: "op01-001-luffy-base",
    catalogItemType: "card",
    provider: "cardmarket",
    providerProductId: "demo-cm-op01-001-base",
    setCode: "OP01",
    cardNumber: "OP01-001",
    variant: "base",
    language: "English",
    condition: "Near Mint",
    region: "EU",
    currency: "EUR",
    primaryPriceField: "trend",
    priceFields: { trend: 5.42, low: 4.89, average1Day: 5.51, average7Days: 5.37, average30Days: 5.08 },
    asOf: "2026-07-16T08:00:00.000Z",
  },
  {
    fixtureId: "demo-tcg-op01-001-base",
    catalogItemId: "op01-001-luffy-base",
    catalogItemType: "card",
    provider: "tcgplayer",
    providerProductId: "demo-tcg-op01-001-base",
    setCode: "OP01",
    cardNumber: "OP01-001",
    variant: "base",
    language: "English",
    condition: "Near Mint",
    region: "US",
    currency: "USD",
    primaryPriceField: "market",
    priceFields: { market: 6.14, low: 5.52, mid: 6.3, high: 8.0, directLow: null },
    asOf: "2026-07-16T08:00:00.000Z",
  },
  {
    fixtureId: "demo-cm-op01-016-parallel",
    catalogItemId: "op01-016-nami-parallel",
    catalogItemType: "card",
    provider: "cardmarket",
    providerProductId: "demo-cm-op01-016-parallel",
    setCode: "OP01",
    cardNumber: "OP01-016",
    variant: "parallel",
    language: "English",
    condition: "Near Mint",
    region: "EU",
    currency: "EUR",
    primaryPriceField: "trend",
    priceFields: { trend: 162.4, low: 149.0, average1Day: 165.8, average7Days: 160.1, average30Days: 151.7 },
    asOf: "2026-07-16T08:00:00.000Z",
  },
  {
    fixtureId: "demo-tcg-op01-016-parallel",
    catalogItemId: "op01-016-nami-parallel",
    catalogItemType: "card",
    provider: "tcgplayer",
    providerProductId: "demo-tcg-op01-016-parallel",
    setCode: "OP01",
    cardNumber: "OP01-016",
    variant: "parallel",
    language: "English",
    condition: "Near Mint",
    region: "US",
    currency: "USD",
    primaryPriceField: "market",
    priceFields: { market: 181.25, low: 169.99, mid: 187.0, high: 215.0, directLow: 176.5 },
    asOf: "2026-07-16T08:00:00.000Z",
  },
  {
    fixtureId: "demo-cm-op05-119-manga",
    catalogItemId: "op05-119-luffy-manga",
    catalogItemType: "card",
    provider: "cardmarket",
    providerProductId: "demo-cm-op05-119-manga",
    setCode: "OP05",
    cardNumber: "OP05-119",
    variant: "manga parallel",
    language: "English",
    condition: "Near Mint",
    region: "EU",
    currency: "EUR",
    primaryPriceField: "trend",
    priceFields: { trend: 2275.0, low: 2150.0, average1Day: null, average7Days: 2298.0, average30Days: 2380.0 },
    asOf: "2026-07-16T08:00:00.000Z",
  },
  {
    fixtureId: "demo-tcg-op05-119-manga",
    catalogItemId: "op05-119-luffy-manga",
    catalogItemType: "card",
    provider: "tcgplayer",
    providerProductId: "demo-tcg-op05-119-manga",
    setCode: "OP05",
    cardNumber: "OP05-119",
    variant: "manga parallel",
    language: "English",
    condition: "Near Mint",
    region: "US",
    currency: "USD",
    primaryPriceField: "market",
    priceFields: { market: 2499.95, low: 2349.99, mid: 2599.0, high: 2899.0, directLow: null },
    asOf: "2026-07-16T08:00:00.000Z",
  },
  {
    fixtureId: "demo-cm-op06-118-parallel",
    catalogItemId: "op06-118-zoro-parallel",
    catalogItemType: "card",
    provider: "cardmarket",
    providerProductId: "demo-cm-op06-118-parallel",
    setCode: "OP06",
    cardNumber: "OP06-118",
    variant: "parallel",
    language: "English",
    condition: "Near Mint",
    region: "EU",
    currency: "EUR",
    primaryPriceField: "trend",
    priceFields: { trend: 78.2, low: 71.5, average1Day: 79.1, average7Days: 77.3, average30Days: 82.6 },
    asOf: "2026-07-16T08:00:00.000Z",
  },
  {
    fixtureId: "demo-tcg-op06-118-parallel",
    catalogItemId: "op06-118-zoro-parallel",
    catalogItemType: "card",
    provider: "tcgplayer",
    providerProductId: "demo-tcg-op06-118-parallel",
    setCode: "OP06",
    cardNumber: "OP06-118",
    variant: "parallel",
    language: "English",
    condition: "Near Mint",
    region: "US",
    currency: "USD",
    primaryPriceField: "market",
    priceFields: { market: 86.45, low: 79.0, mid: 88.0, high: 104.0, directLow: 83.25 },
    asOf: "2026-07-16T08:00:00.000Z",
  },
  {
    fixtureId: "demo-cm-op05-booster-box",
    catalogItemId: "op05-booster-box-english",
    catalogItemType: "sealed-product",
    provider: "cardmarket",
    providerProductId: "demo-cm-op05-booster-box",
    setCode: "OP05",
    language: "English",
    condition: "Sealed",
    region: "EU",
    currency: "EUR",
    primaryPriceField: "trend",
    priceFields: { trend: 184.9, low: 172.0, average1Day: 186.0, average7Days: 181.5, average30Days: 169.4 },
    asOf: "2026-07-16T08:00:00.000Z",
  },
  {
    fixtureId: "demo-tcg-op05-booster-box",
    catalogItemId: "op05-booster-box-english",
    catalogItemType: "sealed-product",
    provider: "tcgplayer",
    providerProductId: "demo-tcg-op05-booster-box",
    setCode: "OP05",
    language: "English",
    condition: "Sealed",
    region: "US",
    currency: "USD",
    primaryPriceField: "market",
    priceFields: { market: 207.3, low: 194.5, mid: 214.0, high: 239.0, directLow: null },
    asOf: "2026-07-16T08:00:00.000Z",
  },
  {
    fixtureId: "demo-cm-st10-deck",
    catalogItemId: "st10-ultra-deck-english",
    catalogItemType: "sealed-product",
    provider: "cardmarket",
    providerProductId: "demo-cm-st10-deck",
    setCode: "ST10",
    language: "English",
    condition: "Sealed",
    region: "EU",
    currency: "EUR",
    primaryPriceField: "trend",
    priceFields: { trend: 31.75, low: 28.9, average1Day: 31.2, average7Days: 30.8, average30Days: 29.1 },
    asOf: "2026-07-16T08:00:00.000Z",
  },
  {
    fixtureId: "demo-tcg-st10-deck",
    catalogItemId: "st10-ultra-deck-english",
    catalogItemType: "sealed-product",
    provider: "tcgplayer",
    providerProductId: "demo-tcg-st10-deck",
    setCode: "ST10",
    language: "English",
    condition: "Sealed",
    region: "US",
    currency: "USD",
    primaryPriceField: "market",
    priceFields: { market: 35.6, low: 32.25, mid: 36.5, high: 42.0, directLow: 34.9 },
    asOf: "2026-07-16T08:00:00.000Z",
  },
];

