begin;

-- Supabase no longer grants Data API access to new public tables by default.
-- The catalog synchronizer uses a backend secret whose database role is
-- service_role, so grant only the tables and operations that importer calls.
-- Browser roles keep their existing, narrower RLS-backed privileges.
grant usage on schema public to service_role;

grant select, insert, update on table
  public.games,
  public.pricing_providers,
  public.card_sets,
  public.cards,
  public.card_variants,
  public.sealed_products,
  public.provider_catalog_mappings,
  public.price_snapshots
to service_role;

grant select on table public.collection_items to service_role;

-- price_snapshots.id is generated by this identity sequence when PostgREST
-- inserts a normalized observation without supplying an explicit row ID.
grant usage, select on sequence public.price_snapshots_id_seq to service_role;

-- Opaque sb_secret_ keys authorize requests as the service_role database role
-- but are not user JWTs. Authorization for this SECURITY DEFINER boundary is
-- therefore the explicit EXECUTE grant, not a JWT-claim check that would tie
-- the job to the deprecated legacy service-role JWT format.
create or replace function public.run_collection_daily_valuation_capture(
  p_snapshot_date date default ((now() at time zone 'UTC')::date)
)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
begin
  return private.capture_collection_daily_valuations_after_prices(p_snapshot_date);
end;
$$;

revoke execute on function public.run_collection_daily_valuation_capture(date)
  from public, anon, authenticated, service_role;
grant execute on function public.run_collection_daily_valuation_capture(date)
  to service_role;

commit;
